<option value="Mombasa">1. Mombasa</option>
<option value="Kwale">2. Kwale</option>
<option value="Kilifi">3. Kilifi</option>
<option value="Tana River">4. Tana River</option>
<option value="Lamu">5. Lamu</option>
<option value="Taita/Taveta">6. Taita/Taveta</option>
<option value="Garissa">7. Garissa</option>
<option value="Wajir">8. Wajir</option>
<option value="Mandera">9. Mandera</option>
<option value="Marsabit">10. Marsabit</option>
<option value="Isiolo">11. Isiolo</option>
<option value="Meru">12. Meru</option>
<option value="Tharaka-Nithi">13. Tharaka-Nithi</option>
<option value="Embu">14. Embu</option>
<option value="Kitui">15. Kitui</option>
<option value="Machakos">16. Machakos</option>
<option value="Makueni">17. Makueni</option>
<option value="Nyandarua">18. Nyandarua</option>
<option value="Nyeri">19. Nyeri</option>
<option value="Kirinyaga">20. Kirinyaga</option>
<option value="Muranga">21. Murang'a</option>
<option value="Kiambu">22. Kiambu</option>
<option value="Turkana">23. Turkana</option>
<option value="West Pokot">24. West Pokot</option>
<option value="Samburu">25. Samburu</option>
<option value="Trans Nzoia">26. Trans Nzoia</option>
<option value="Uasin Gishu">27. Uasin Gishu</option>
<option value="Elgeyo/Marakwet">28. Elgeyo/Marakwet</option>
<option value="Nandi">29. Nandi</option>
<option value="Baringo">30. Baringo</option>
<option value="Laikipia">31. Laikipia</option>
<option value="Nakuru">32. Nakuru</option>
<option value="Narok">33. Narok</option>
<option value="Kajiado">34. Kajiado</option>
<option value="Kericho">35. Kericho</option>
<option value="Bomet">36. Bomet</option>
<option value="Kakamega">37. Kakamega</option>
<option value="Vihiga">38. Vihiga</option>
<option value="Bungoma">39. Bungoma</option>
<option value="Busia">40. Busia</option>
<option value="Siaya">41. Siaya</option>
<option value="Kisumu">42. Kisumu</option>
<option value="Homa Bay">43. Homa Bay</option>
<option value="Migori">44. Migori</option>
<option value="Kisii">45. Kisii</option>
<option value="Nyamira">46. Nyamira</option>
<option value="Nairobi City">47. Nairobi City</option>